spring:
management.endpoint.shutdown.enabled: true
backend:
  repositoryUrl: http://onto.fel.cvut.cz:7200/repositories/kodi-pracovni-prostor-sample
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    cz.cvut.kbss: TRACE

