spring:
#  main.allow-bean-definition-overriding: true

jwt.secretKey: SecretKey

server.port: 49080
repository:
  url: https://onto.fel.cvut.cz:7200/repositories/kodi-pracovni-prostor-validace

persistence:
  driver: cz.cvut.kbss.ontodriver.sesame.SesameDataSource
  language: cs

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    cz.cvut.kbss: INFO