application:
  version: ${version}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

info.app:
  name: "SGoV Server"
  description: "This is SGoV Server, see https://github.com/opendata-mvcr/sgov for details."
  version: ${version}

spring:
  output:
    ansi:
      enabled: DETECT

server:
  port: 18189
  servlet:
    contextPath: /sgov-server

jwt.secretKey: SecretKey

repository:
  url: https://onto.fel.cvut.cz:7200/repositories/kodi-uloziste-dev
  releaseSparqlEndpointUrl: https://slovník.gov.cz/sparql
  githubRepo: ssp
  githubOrganization: opendata-mvcr
  githubUserToken: \${GITHUB_USER_TOKEN}

persistence:
  driver: cz.cvut.kbss.ontodriver.sesame.SesameDataSource
  language: cs

keycloak:
  configurationFile: classpath:keycloak.json

logging:
  pattern:
#    console: "%black(%d{dd-MM-yyyy HH:mm:ss.SSS}) [%X{username}] [%blue(thread)] %highlight(%-5level) %logger{36} - %yellow(%msg) %n%throwable"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%X{username}] [thread] %-5level %logger{36} - %msg %n%throwable"
  level:
    root: INFO
    com.github.sgov: INFO
    org.springframework.web: INFO