name: Build docker
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: al-sgov-server
  USERNAME: ${{ github.actor }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Gradle 7.1.1
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1.1

      - name: Build JAR
        run: gradle clean bootJar
        
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
        
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          IMAGE_TAG=${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
          echo IMAGE_TAG=$IMAGE_TAG
          docker tag $IMAGE_NAME $IMAGE_TAG
          docker push $IMAGE_TAG

  
  update-dev-instance:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Call update webhook
        uses: wei/curl@v1.1.1
        with:
          args: |
            -H \"X-Secret: ${{ secrets.AL_DEV_SECRET }}\" -X POST https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/update/${{ env.IMAGE_NAME }}.php
