name: Build
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  USERNAME: ${{ github.actor }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build JAR
        run: gradle clean build

      - name: Test
        run: gradle test
